### ISSUE TITLE
Dotnet Test command in Azure yaml has no "--no-build" command

### ISSUE THREAD

**Issue by JeffreyZacher** [TroyWalshProf/SeleniumAxeDotnet#55]
the yaml specifics a build then a test run

test run triggers a second build

```yml
- script: dotnet build --no-restore -c $(buildConfiguration) -p:Version=$(version)
  displayName: dotnet build
  workingDirectory: $(solutionDirectory)

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solutionDirectory)\Selenium.Axe.Test\Selenium.Axe.Test.csproj'
    arguments: '--collect:"Code Coverage"'
```
